export const  GET_ALL_TASK_TYPE = 'GET_ALL_TASK_TYPE'
export const GET_ALL_TASK_TYPE_SAGA = 'GET_ALL_TASK_TYPE_SAGA'
export const GET_ALL_PRIORITY = 'GET_ALL_PRIORITY'
export const GET_ALL_PRIORITY_SAGA = 'GET_ALL_PRIORITY_SAGA'